image: node:14.18.0

pages:
  stage: deploy
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - npm run build
  - rm -rf public
  - cp build/index.html build/404.html
  - mv build public
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
